### PR TITLE
[FEATURE] Proxy Backend Services

### PR DESCRIPTION
**Pull request by MichaelSp**
fixes https://github.com/SAP/ui5-server/issues/13

Signed-off-by: Michael Sprauer <Michael.Sprauer@sap.com>

### CODE REVIEW

**Comment by vobu** [comment]
@petermuessig should this take precedence over our https://github.com/petermuessig/ui5-ecosystem-showcase/tree/master/packages/ui5-middleware-simpleproxy ?

**Comment by RandomByte** [comment]
Hey @MichaelSp and @Schoutenk,

Thank you for working on this important topic. We are still not sure whether this specific solution fits into the standard UI5 Tooling.

However, I think you should be able to make this a custom middleware (see our [documentation](https://sap.github.io/ui5-tooling/pages/extensibility/CustomServerMiddleware/)). This would allow for easy reuse with the latest versions of the UI5 CLI for anyone interested in using this proxy setup. What do you think?

**Comment by vobu** [comment]
> We are still not sure whether this specific solution fits into the standard UI5 Tooling.

i'm just wondering what the rationale against a generic proxy being part of the ui5 tooling is. can you elaborate please?

**Comment by petermuessig** [comment]
@vobu the main issue with a generic proxy is that this will and cannot satisfy all needs, unfortunately. One needs authentication, the next needs a different path processing or the proxy should consider the neo-app.json or the xs-app.json or whatever other configuration file. I personally would prefer that the people understand the extensibility and can easily implement or better *share* their proxy with the community. It is good, that we provide an open-source tooling, but it is better when the community can contribute to the tooling by providing own middlewares.

**Comment by MichaelSp** [comment]
@RandomByte I've abandond the ui5 and thus ui5-tooling and switched to https://github.com/SAP/fundamental-styles instead. So I'm fine with whatever decision you make.

**Comment by vobu** [comment]
> It is good, that we provide an open-source tooling, but it is better when the community can contribute to the tooling by providing own middlewares.

right on - so @Schoutenk, what would you think about moving this proxy solution over to https://github.com/petermuessig/ui5-ecosystem-showcase?

**Comment by Schoutenk** [comment]
@vobu,
That would be fine with me. I understand it would not fit as a generic solution for everyone. I'll use the middleware instead.

**Comment by petermuessig** [comment]
@Schoutenk very nice! thanks for creating and publishing your middleware. They basic auth part could also be added to the simple proxy in the ecosystem repository - but with an extra middleware I am fine as well. In general, contribution to the ecosystem showcase repository are welcome. We could add there also special middlewares in order to keep the UI5 tooling as general as possible and as extensible as possible. Thanks for your understanding and your work!

**Comment by petermuessig** [comment]
@MichaelSp @Schoutenk - I will try to setup a WIKI-like page in the UI5 ecosystem showcase repository , which will allow to list the https://github.com/Schoutenk/ui5-middleware-proxy-basicauth - with that anyone can use it and we keep the server free from the proxy feature. Are you ok with that?

**Comment by Schoutenk** [comment]
> @MichaelSp @Schoutenk - I will try to setup a WIKI-like page in the https://github.com/petermuessig/ui5-ecosystem-showcase/ , which will allow to list the https://github.com/Schoutenk/ui5-middleware-proxy-basicauth - with that anyone can use it and we keep the server free from the proxy feature. Are you ok with that?

Of course. That would be great!

**Comment by petermuessig** [comment]
The Wiki-like-page can be found here: https://petermuessig.github.io/ui5-ecosystem-showcase/ - you can contribute to it - that would be great! :-)

**Comment by petermuessig** [comment]
As discussed above, instead of making the proxy part of the ui5-server we prefer to have middleware plugins for the proxy solutions.

**Pull request closed without merging**
