### PR TITLE
[FEATURE] serveIndex: use serve-index for serving the application index

### PR DESCRIPTION
**Pull request by jkoenig134**
## My changes

- using https://www.npmjs.com/package/serve-index for serving index files
- Index is now more user-friendly
- implements possibility for @ui5/cli to show hidden files and choose a view (tiles or details)
  createMiddleware has now therefore 3 arguments (the new one are optional -> no beaking changes
  `createMiddleware({resources, tiles, showHidden})`
  - the resources object stays the same
  - the tiles object `boolean` declares if the ui should show tiles or a detailed table
  - the showHidden `boolean` declares if dot files should be hidden or not
  

## Pull Request Checklist
- [x] Reviewed the [Contributing Guidelines](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#-contributing-code)
    + Especially the [How to Contribute](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#how-to-contribute) section 
- [x] [No merge commits](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#no-merge-commits)
- [x] [Correct commit message style](https://github.com/SAP/ui5-tooling/blob/master/docs/Guidelines.md#commit-message-style)

### CODE REVIEW

**Comment by jkoenig134** [comment]
I had to change some of the tests, caused by many UI improvements. This should be the reason why those build nodes are failing. 😢 
On my machine `npm test` shows green light.

**Comment by jkoenig134** [comment]
Hey @RandomByte, thank you very much for approval and merging!
I will add a PR at @ui5/cli soon, for integration of the `tiles` and `hidden` functionalities.

**Comment by jkoenig134** [comment]
@RandomByte the options are beeing exposed in my new pull request for @ui5/server, upcoming in the next minutes. I TOTALLY forgot this in the last PR...

**Comment by RandomByte** [comment]
Released as part of UI5 CLI [`v1.12.0`](https://github.com/SAP/ui5-cli/releases/tag/v1.12.0) 🎉

**Comment by jkoenig134** [comment]
🎉🎉🎉🎉

**Comment by vobu** [comment]
i have talented colleagues, yeah

**Pull request merged**
