### PR TITLE
[DEPENDENCY] Bump path-to-regexp, router and sinon

### PR DESCRIPTION
**Pull request by d3xter666**
The same issue as here https://github.com/SAP/ui5-server/pull/694, but for UI5 Tooling v3

### CODE REVIEW

**Comment by flovogt** [comment]
sinon 17 has dropped node 16 support. So upgrading sinon higher than 16 would be a breaking change

**Comment by RandomByte** [comment]
> sinon 17 has dropped node 16 support. So upgrading sinon higher than 16 would be a breaking change

Although tests seem to be passing fine 😅

**Comment by RandomByte** [comment]
I think it's fine, better to fix the vulnerable dependency. @matz3 any objections?

**Review by RandomByte — APPROVED** [review]
Let's go

**Pull request merged**
