### PR TITLE
providing app instance in a middleware plugin

### PR DESCRIPTION
**Pull request by ThePlenkov**
Hi! 

I was playing a bit with custom middleware and figured out that is completely inconvenient not to have app instance in the callback.

even if it's available in req.app - it will be already too late to declare custom routes 

Especially this change is important if plugin brings composite feature.

Please review a following project which already has this PR included:

https://github.com/ThePlenkov/openui5-sample-app

Thank you!

### CODE REVIEW

**Comment by ThePlenkov** [comment]
> [CLA assistant check](https://cla-assistant.io/SAP/ui5-server?pullRequest=239)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/ui5-server?pullRequest=239) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/ui5-server?pullRequest=239) it.

I already signed it coulple times and re-check. It seems that this button is stuck somehow

**Comment by matz3** [comment]
CLA is fine 👍 You can ignore the 2nd comment.

**Comment by matz3** [comment]
Closing as this can be done already with the express.Router as explained here: https://github.com/SAP/ui5-server/issues/240#issuecomment-535055185.

**Comment by kingclowndean** [comment]
https://github.com/SAP/ui5-server/pull/239

**Pull request closed without merging**
